const sayings = [
  "",
  "把問題往後推 問題反而會緊跟其後",
  "理性與感性的界線在好奇心",
  "There's only one way to avoid criticism: do nothing, say nothing, and be nothing.--- Aristotle",
  "Genius is in the idea. Impact comes from action. --- Together is better",
  "The best way to find out if it will work is to do it. --- Together is better",
  "To go fast, go alone. To go far, go together. --- African proverb",
  "Precision Beats Power, Timing Beats Speed --- Conor McGregor",
  "保持距離才能安穩飛翔",
  "永遠不夠糟到會往下掉，但也永遠不夠好到可以贏得任何東西，那停滯的狀態讓你沮喪到想要尖叫。--- Fever Pitch",
  "無論多麼精明，也無法改變一個事實：所有的知識都是關於過去的，所有的決定都是關於未來的。--- Ian E. Wilson",
  "知者不言，言者不知。--- 老子",
  "人們只能預見恰巧符合他們意願的未來，而那些最為明顯的事實在不受歡迎之時將被忽視。--- 喬治·奧威爾",
  "預測創造了未來可知的海市蜃樓。--- 彼得·伯恩斯坦",
  "我從不考慮未來，它旋即就到。--- 阿爾伯特·愛因斯坦",
  "在未來到來的時候你自然就會知道，在此之前，不要管它。--- 埃斯庫羅斯",
  "預測通常告訴我們更多預測者自身的情況，而並非未來。--- 沃倫·巴菲特",
  "三個點才可以拉出一個平面,這是三元理論的基礎",
  "假裝是沒有用的，你必須持續假裝，才有可能看起來像真的。",
  "這個圈子很小，也許是你沒有走出去",
  "我們總是騎著大象去摸象",
  "原則上，原則是用來打破的…",
  "知之為知之，不知為不知 --- 孔子",
  "論語告訴我們的事，古代就有毒雞湯",
  "Black Lives Matter 那個不要文字獄",
  "別問，你也會這樣作，不然那就是我為什麼比你優秀的地方",
  "習慣面對失敗，而不是習慣失敗",
  "如果我擁有改變世界的神奇力量，我會希望在不造成痛苦和折磨下，減少地球人口。 --- Jane Goodall",
  "因為我們的數量太多了，我們快要將地球有限的資源消耗完了，這代表未來將會有很多苦難。--- Jane Goodall",
  "Tradition is not the worship of ashes, but the preservation of fire. --- Gustav Mahler",
  "要多成熟，才能自然的說出「我很幼稚」呢?",
  "Design is not just what it looks like and feels like. Design is how it works. --- Steve Jobs",
  "成熟是種無奈，長大是種必然",
  "Never mistake motion for action --- Hemingway",
  "天堂裡沒有幽默，因為幽默的祕密來源不是喜悅，而是悲傷。 --- Mark Twain",
  "不要停止懷疑，不要停止信仰",
  "在我左邊，我太右;在你左邊，我太左。我在哪裡？世界是圓的，而你是中心。",
  "Those who can, do, and those who can't, teach.",
  "良好的習慣不是枷鎖，而是讓你更忠於自已",
  "寧靜致遠，淡泊明志",
  "In the future, everyone will be world-famous for 15 minutes. --- Andy Warhol",
  "Any fool can write code that a computer can understand. Good programmers write code that humans can understand --- Martin fowler",
  "沒有對立，沒有中立",
  "明亮寧靜，而又清澈懷念的文體，帶著一絲小任性，充滿了嚴格和深奧的文體，宛如夢境般的美麗化為現實的真切文體。 --- 原民喜",
  "When to use iterative development? You should use iterative development only on projects that you want to succeed. --- Martin Fowler",
  "Make It Work Make It Right Make It Fast --- KentBeck",
  "Premature optimization is the root of all evil --- Donald Knuth",
  "Where 'work' is making tests pass, 'right' is refactoring the code, and 'fast' is optimizing the code --- Learn Go with tests",
  "When life seems hard, the courageous do not lie down and accept defeat;instead, they are all the more determined to struggle for a better future.",
  "學習並不是追求更多的知識，而是要尋找更好的決策依據 - Charles Munger.",
  "幸福的祕密，就是去欣賞世界上所有的奇特景觀，但不要忘了湯匙裡的油。 --- 牧羊少年奇幻之旅",
  "你人生的快樂取決於你思想的品質 --- Marcus Aurelius",
  "我們在想像中受的苦比在現實中還多 --- Lucius Annaeus Seneca minor",
  "He who can, does. He who cannot, teaches",
  "На свете счастья нет, но есть покой и воля. --- Александр Пушкин(世上沒有幸福，但有寧靜和自由。 --- 普希金) ",
  "Elegance doesn't mean being noticed, it means being remembered  --- Giorgio Armani",
  "人間の怒りには、真っ赤に爆発するものと……静かにゆらぎながら……真っ青に燃え続けるものがあるのさ。 --- ギイ・クリストフ・レッシュ"
]
